name: Validate YAML Recommendations

on:
  pull_request:
    branches:
      - main
      - dev-tools
    paths:
    - '**/*.yaml'
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  yaml_file_check:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Set up Python 3.x
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.x

      - name: Run YAML file check
        run: |
          python -u .github/scripts/validate-yaml-recommendations.py


